function SRC_ID = importSRC_ID(year, column, fileadress)
%importSRC_ID Import numeric data SRC_ID from a houly rainfall text file as a matrix.
%   SRC_ID = importSRC_ID(FILENAME) Reads data from text
%   file FILENAME is decided by YEAR.
%
%   SRC_ID = importSRC_ID(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   SRC_ID = importSRC_ID(1915, 1, 2855); filename is
%   'midas_rainhrly_191501-191512.txt'
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/05/28 11:57:34
% Renewed on 2015/11/25
%% Initialize variables.
if column==7    
    filehead = 'midas_rainhrly_';           
elseif column==8
    filehead = 'midas_raindrnl_';
else
    error('Invalid function parameters')
end
filetail = '.txt';
filename = [fileadress, filehead, num2str(year),'01-',num2str(year),'12',filetail];
delimiter = ',';

%% Format string for each line of text:
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
if column == 7
    formatSpec = '%*s%*s%*s%*s%*s%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';
elseif column == 8
    if year > 2010
        formatSpec = '%*s%*s%*s%*s%*s%*s%*s%f%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';
    else
        formatSpec = '%*s%*s%*s%*s%*s%*s%*s%f%*s%*s%*s%*s%*s%*s%[^\n\r]';
    end
end
%% Open the text file.
fileID = fopen(filename,'r');

%%Read columns of data according to format string.

dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);
%%Close the text file.
fclose(fileID);


%% Create output variable
SRC_ID = dataArray{:, 1};

end
