function F = ArchimCopulaCDF(cname,u,alpha)
claytoncdf = @(u1,u2,alpha) (1 +(u1.^(-alpha)-1+u2.^(-alpha)- 1)).^(-1./alpha);
frankcdf = @(u1,u2,alpha) ...
    -1/alpha .* log(1 + exp(-(-log((exp(-alpha .*...
    u1) - 1)./(exp(-alpha) - 1)) + -log((exp(-alpha .* u2) - 1)./(exp(-alpha) -...
    1)))) .* (exp(-alpha) - 1));
gumbelcdf = @(u1,u2,alpha) ...
    exp(-((-log(u1)).^alpha + (-log(u2)).^alpha).^(1/alpha));
amhcdf = @(u1,u2,alpha)...
    (1-alpha)./(exp(log((1-alpha.*(1-u1))./u1)+ log((1-alpha.*(1-u2))./u2))-alpha);
frankcdf3 = @(u1,u2,u3,alpha)...
    -1/alpha * log(...
    1 + exp(-(...
    -log((exp(-alpha*u1)-1)./(exp(-alpha)-1))...
    + -log((exp(-alpha * u2) - 1)./(exp(-alpha)-1))...
    + -log((exp(-alpha * u3) - 1)./(exp(-alpha) - 1))...
    ))...
    *(exp(-alpha) - 1)...
    );
claytoncdf3 = @(u1,u2,u3,alpha)...
    (1 + ...
    ( u1.^(-alpha) - 1 + u2.^(-alpha) - 1 + u3.^(-alpha) - 1)...
    )...
    .^(-1./alpha);
gumbelcdf3 = @(u1,u2,u3,alpha)...
    exp(-((-log(u1)).^alpha + (-log(u2)).^alpha +...
    (-log(u3)).^alpha).^(1/alpha));

u1=u(:,1);u2=u(:,2);
if size(u,2)==3
    u3 = u(:,3);
    if strcmpi(cname,'clayton')
        F = claytoncdf3(u1,u2,u3,alpha);
    elseif strcmpi(cname,'frank')
        F = frankcdf3(u1,u2,u3,alpha);
    elseif strcmpi(cname,'gumbel')
        F = gumbelcdf3(u1,u2,u3,alpha);
    else
        error(['do not surpport 3D copula ' cname])
    end
else
    if strcmpi(cname,'clayton')
        F = claytoncdf(u1,u2,alpha);
    elseif strcmpi(cname,'frank')
        F = frankcdf(u1,u2,alpha);
    elseif strcmpi(cname,'gumbel')
        F = gumbelcdf(u1,u2,alpha);
    elseif strcmpi(cname,'amh')
        F = amhcdf(u1,u2,alpha);
    else
        error(['do not surpport 2D copula ' cname])
    end
end
end
